### ISSUE TITLE
Device creation unreliable 

### ISSUE THREAD

**Issue by Koshu** [danielperna84/home-assistant#14] opened 2016-06-26 11:15 UTC
After the startup of HA the devices don't always get created correctly.

This happens always for an complete category of devices (thermostats, binary_sensors ...). Sometimes only one category, sometimes multiple in any combination.

Waiting doesn't help, only restarting and hoping that it works this time. If all categories started up correctly everything is working fine, however.

As far as I can tell there are no meaningful entries in the debug log. Attached a log of the component full working and one where the binary_sensors failed, anyway.

[everything_ok.txt](https://github.com/danielperna84/home-assistant/files/333531/everything_ok.txt)

[binary_sensors_not_detected.txt](https://github.com/danielperna84/home-assistant/files/333532/binary_sensors_not_detected.txt)

If you can tell me how, I will try to provide you with more information.

Greets

**Comment by danielperna84** [comment] 2016-06-26 14:33
Please pull the latest code from here: https://github.com/pvizeli/home-assistant/tree/Homematic/homeassistant/components
I had similar issues which I could not reproduce. I've done some changes with the exception handling, and now it doesn't happen anymore that a complete category fails.

It would be interesting to know, if the devices that don't work for you with auto detection will work if you configure them manually. As it is stated, the autodetection is more experimental to give new users a glimpse of which devices they own are supported. In the long run it makes more sense to manually configure the devices. As long as manual configuration doesn't fail, I'd consider this bug very minor.

**Comment by Koshu** [comment] 2016-06-26 14:46
I pulled it from pvizelis repo (I updated last time this morning). For some reason I don't see an Issue button on his repo, that's why i reported here. Is the Issue tracker disabled? Or where is the right place to report bugs?

I never used the auto discovery. Everything is configured manually. If a category isn't working the device get displayed as unavailable in the webinterface.

**Comment by danielperna84** [comment] 2016-06-26 15:01
Yes, his repo hass issue tracking disabled. It's ok to open the issues here. :)
The code from this morning is the most recent, and I used it sucessfully with auto-detection with abount 20 devices of all kinds. So my guess would be, that there is somethign wrong with your configuration.

From looking at your logoutput it seems as if Bettlampe is the device that fails. Can you show me your configuration for that device?
Additionally it would be helpful to also see the logs HA creates. Not DEBUG, the INFO level is enough here. Where it's telling which platforms it is setting up, also possible exception could be there.

**Comment by Koshu** [comment] 2016-06-26 16:04
Its not always the Bettlampe where it stops. Completely random. Attached my configs for the homematic devices and the log. 

[HA_info_log.txt](https://github.com/danielperna84/home-assistant/files/333675/HA_info_log.txt)
[thermostats.yaml.txt](https://github.com/danielperna84/home-assistant/files/333674/thermostats.yaml.txt)
[binary_sensors.yaml.txt](https://github.com/danielperna84/home-assistant/files/333676/binary_sensors.yaml.txt)
[switches.yaml.txt](https://github.com/danielperna84/home-assistant/files/333677/switches.yaml.txt)

I'm not quite sure but this problem might be related to my homegear issue.

**Comment by danielperna84** [comment] 2016-06-26 16:14
Yes, it could be indeed related to your HG issue. The configs look good, and the HA-log doesn't provide information that would help finding the cause of the problem.
Could you set the log-level for the homematic-component to DEBUG? Maybe that provides some hints.

**Comment by Koshu** [comment] 2016-06-26 16:37
Ok interesting. Because i'm to lazy to clean all the more sensitive data out of the debug log I disabled everything expect the homematic components. Now as long as HA manages to connects to HG (the other issue) it detects all the devices every time. Will try to enable them one by one and see at what point it reappears.

**Comment by Koshu** [comment] 2016-06-26 17:09
There dosn't seem to be one component that causes this behaviour. It more like the more components I enable the more likely it is that devices don't get detected/connected. 

Is there maybe some time critical code?

Debug log (this time the thermometers didn't show up):
[debug_log_thermo_missing.txt](https://github.com/danielperna84/home-assistant/files/333695/debug_log_thermo_missing.txt)

**Comment by danielperna84** [comment] 2016-06-26 17:25
Can you please replace the component-code (components/homematic.py) with this code?
http://pastebin.com/DZDH9qVq
I've added 3  try/except blocks at the locations where the errors might occur. If they are caused by unexpected exceptions, we would now see them.

**Comment by Koshu** [comment] 2016-06-26 17:47
Here you go. This time with 2 of the 3 thermometers missing (guess its not always a complete category). 
Couldn't see any new ouput.

[debug_log_thermo_missing.txt](https://github.com/danielperna84/home-assistant/files/333714/debug_log_thermo_missing.txt)

**Comment by danielperna84** [comment] 2016-06-26 18:00
Indeed, nothing suspicious.
How many devices to you have configured, and who many other platforms/components that are not homematic? Of which kind are they? And is there a reproducible amount of non-homematic entites that triggers the problem?

**Comment by danielperna84** [comment] 2016-06-26 18:10
The updater-error is irrelevant. That probably is because the updater is disabled when using HA in dev-environments.

**Comment by Koshu** [comment] 2016-06-26 19:04
Here is my config (without passworts etc of course):

[config.zip](https://github.com/danielperna84/home-assistant/files/333747/config.zip)

Going from top to bottom its starts after I activated the telegram notify component. However disabling telegram and enabling something else does the same thing.

In case performance is relevant, i'm running everything on an Asro Q1900DC-ITX Celeron J1900. All the homeautomation stuff is in a virtual machine.

**Comment by danielperna84** [comment] 2016-06-26 19:39
Meanwhile @pvizeli hass updated THIS repository and also added some debug messages that can help us find the error. We have decided, that we will use this repositore for testing, development etc., and his will use the final changes from here that we will push to HA. Sorry for the incovenience.

So, please switch back to this repository und post the logoutput. Additionally, please set the loglevel of pyhomematic to debug as well. So have it like this.

```yaml
logger:
  default: info
  logs:
    homeassistant.components.homematic: debug
    pyhomematic: debug
```

I will look at your zip meanwhile.

**Comment by Koshu** [comment] 2016-06-26 20:12
Can try that but i think I found the root of the problem. Just went and spammed my homematic.py with debug messages. Now, I don't have a complete knowledge about the structure of the component, pyhomatic or HA itself, so correct my if my following assumptions are wrong:

The functions that came to my attention are system_callback_handler and setup_hmdevice_entity_helper. Now I'm guessing that system_callback_handler is called from the pyhomatic side, while setup_hmdevice_entity_helper is called from the HA side (right?). What ever is the case, what i noticed is, that all device get created where the setup_hmdevice_entity_helper is called before(!) system_callback_handler. All devices where the system_callback_handler is to "late" the connection can't be established because in the lines
```
                    for hm_element in HOMEMATIC_DEVICES[dev]:
                        hm_element.link_homematic(delay=delay)
```
they won't be found. Unless you have the autodiscovery enabled. In that case it gets created anyway but since i never enabled autodiscovery, that didn't work for me.

This would also explain, why it only happens with many other components enabled, because it delays the creation of the devices and the call of setup_hmdevice_entity_helper.

I attached my "modified" homematic.py and a logoutput where only the device MEQ0272917 is created, which is the only on with a setup_hmdevice_entity_helper call before the system_callback_handler call.

[log.txt](https://github.com/danielperna84/home-assistant/files/333794/log.txt)


[homematic.py.txt](https://github.com/danielperna84/home-assistant/files/333796/homematic.py.txt)


I guess a dirty solution would be to delay the system_callback_handler and a nicer one to track devices in both directions.

Greets

**Comment by Koshu** [comment] 2016-06-26 20:17
One additional question: What is "THIS" repository. There is no link. The on pvizeli made or anew one?

**Comment by danielperna84** [comment] 2016-06-26 20:20
No, I meant this one where we are in right now. The one from @pvizeli will be the on where we will push changes we make here.

For the rest: interesting observation!

**Comment by Koshu** [comment] 2016-06-26 20:29
Short update. Made a little change to setup_hmdevice_entity_helper:

```
def setup_hmdevice_entity_helper(hmdevicetype, config, add_callback_devices):
    """Helper to setup Homematic devices."""
    _LOGGER.debug("entity helper %s", config.get('address', None))

    if HOMEMATIC is None:
        _LOGGER.error('Error setting up HMDevice: Server not configured.')
        return False

    address = config.get('address', None)
    if address is None:
        _LOGGER.error("Error setting up device '%s': " +
                      "'address' missing in configuration.", address)
        return False

    # Create a new HA homematic object
    new_device = hmdevicetype(config)
    if address not in HOMEMATIC_DEVICES:
        HOMEMATIC_DEVICES[address] = []
    HOMEMATIC_DEVICES[address].append(new_device)

   #### DIRTY WORKAROUND START HERE ####
    try:
        new_device.link_homematic(delay=0.5)
    except Exception as err:
        _LOGGER.error("setup_hmdevice_entity_helper error linking: %s", str(err))
    
   #### AND ENDS HERE ####

    # Add to HA
    add_callback_devices([new_device])
    return True
```

Now it will try to link every time. Only a dirty workaround and you will probably come up with a cleaner solution but at a first glance it seems to fix the problem.

**Comment by danielperna84** [comment] 2016-06-26 20:45
pvizeli has pushed a fix... Can you please try again?

**Comment by Koshu** [comment] 2016-06-26 21:07
Pulling the new code right now but seems to take quite some time. Will test it tomorrow.

**Comment by Koshu** [comment] 2016-06-27 06:33
Tried a few times and seems fine so far. I guess this bug is fixed. Will keep you updated if still notice something.

Thanks

**Comment by Koshu** [comment] 2016-06-28 18:52
Ok until now device creation works fine. However i noticed something else, that is most likely related to this bug. Auto of curiosity I enabled auto discovery. Now, devices that are manually defined and are created to late by HA are detected two times. Once with the name I gave them in HA and once with their address.

**Comment by danielperna84** [comment] 2016-06-28 19:10
That's strange. What kind of device are you using? Or does that happen to all devices you have?
I'm testing with a door-contact and a thermostat configured, 4 door contacts being auto detected. I get everything as I would expect it.

**Comment by Koshu** [comment] 2016-06-28 19:38
Have to look into it in more detail, but would assume its the same bug just the other way round. One a first glance the devices that appear two times are random in the same manner as they refused to appear before. (not really a major bug for me since I probably turn off auto detection again, just wanted to let you know)

I guess they are getting created in the autodetection part of system_callback_handler and later on again, when setup_hmdevice_entity_helper is called for the same device.

**Comment by danielperna84** [comment] 2016-06-28 19:55
I guess it doesn't happen to me because of my minimal config.

I've talked to @pvizeli , and we have decided that this case is part of what we consider "experimental" with autodetect. Everything should work fine if you either use autodetect OR configure manually. So there is a way to get a fully functional system.

**Comment by danielperna84** [comment] 2016-06-28 21:37
We have changed the default behavior. It won't be possible anymore to manually setup devices. Instead they are always autodetected, and you may rename or hide them using Home Assistans [Customizing](https://home-assistant.io/getting-started/customizing-devices/) feature.
This will be way less effort. You just take the entity ids you get from HA and apply your modifications.

**Comment by Koshu** [comment] 2016-06-29 05:57
Haven't tried that feature jet. Is it possible to use the friendly name in automation and scripts? Would be kind of annoying to always work with the autogenerated address names.

**Comment by pvizeli** [comment] 2016-06-29 07:12
I don't known, but I think that is not possible. If you have HG, you can use the names from this with "resolvenames: True" in the config. For CCU we want Support that in the next pyhomematic release. @danielperna84 is working on.

It do possible to use HA in HM really easy and it is the way uf future in homeautomation on all system (i.e openHab)

**Closed** 2016-06-29 07:13 UTC
Labels: bug
